//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeEnumerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TypeEnumerator.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01, 21, 22, 23, 24.
        /// </summary>
        internal static string MysIcValidStateCodeJohor {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeJohor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02, 25, 26, 27.
        /// </summary>
        internal static string MysIcValidStateCodeKedah {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeKedah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03, 28, 29.
        /// </summary>
        internal static string MysIcValidStateCodeKelantan {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeKelantan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04, 30.
        /// </summary>
        internal static string MysIcValidStateCodeMelaka {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeMelaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05, 31, 59.
        /// </summary>
        internal static string MysIcValidStateCodeNSembilan {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeNSembilan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 06, 32, 33.
        /// </summary>
        internal static string MysIcValidStateCodePahang {
            get {
                return ResourceManager.GetString("MysIcValidStateCodePahang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08, 36, 37, 38 , 39.
        /// </summary>
        internal static string MysIcValidStateCodePerak {
            get {
                return ResourceManager.GetString("MysIcValidStateCodePerak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09, 40.
        /// </summary>
        internal static string MysIcValidStateCodePerlis {
            get {
                return ResourceManager.GetString("MysIcValidStateCodePerlis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07, 34, 35.
        /// </summary>
        internal static string MysIcValidStateCodePPinang {
            get {
                return ResourceManager.GetString("MysIcValidStateCodePPinang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12, 47, 48, 49.
        /// </summary>
        internal static string MysIcValidStateCodeSabah {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeSabah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13, 50, 51, 52, 53.
        /// </summary>
        internal static string MysIcValidStateCodeSarawak {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeSarawak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10, 41, 42, 43, 44.
        /// </summary>
        internal static string MysIcValidStateCodeSelangor {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeSelangor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11, 45, 46.
        /// </summary>
        internal static string MysIcValidStateCodeTerengganu {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeTerengganu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 82.
        /// </summary>
        internal static string MysIcValidStateCodeUnknownState {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeUnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14, 54, 55, 56, 57.
        /// </summary>
        internal static string MysIcValidStateCodeWPKualaLumpur {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeWPKualaLumpur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15, 58.
        /// </summary>
        internal static string MysIcValidStateCodeWPLabuan {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeWPLabuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string MysIcValidStateCodeWPPutrajaya {
            get {
                return ResourceManager.GetString("MysIcValidStateCodeWPPutrajaya", resourceCulture);
            }
        }
    }
}
