//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_TypeEnumerator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_TypeEnumerator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources_TypeEnumerator", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Setup.
        /// </summary>
        internal static string titlePageEmailConfigurationSetup {
            get {
                return ResourceManager.GetString("titlePageEmailConfigurationSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Setup.
        /// </summary>
        internal static string titlePageGeneralConfigurationSetup {
            get {
                return ResourceManager.GetString("titlePageGeneralConfigurationSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string typeEnum_actionafterwarning_cancel {
            get {
                return ResourceManager.GetString("typeEnum.actionafterwarning.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string typeEnum_actionafterwarning_ignore {
            get {
                return ResourceManager.GetString("typeEnum.actionafterwarning.ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string typeEnum_agentRole_agent {
            get {
                return ResourceManager.GetString("typeEnum.agentRole.agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string typeEnum_branchRole_branch {
            get {
                return ResourceManager.GetString("typeEnum.branchRole.branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string typeEnum_branchRole_centre {
            get {
                return ResourceManager.GetString("typeEnum.branchRole.centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string typeEnum_branchRole_group {
            get {
                return ResourceManager.GetString("typeEnum.branchRole.group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Next Run Date.
        /// </summary>
        internal static string typeEnum_configurationName_archiveNextRunDate {
            get {
                return ResourceManager.GetString("typeEnum.configurationName.archiveNextRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Rate.
        /// </summary>
        internal static string typeEnum_configurationName_commissionRate {
            get {
                return ResourceManager.GetString("typeEnum.configurationName.commissionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Age to Archive (Months).
        /// </summary>
        internal static string typeEnum_configurationName_dataAgeToArchiveInMonths {
            get {
                return ResourceManager.GetString("typeEnum.configurationName.dataAgeToArchiveInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Student Age to Register.
        /// </summary>
        internal static string typeEnum_configurationName_minStudentAge {
            get {
                return ResourceManager.GetString("typeEnum.configurationName.minStudentAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Before Expiry Next Run Date.
        /// </summary>
        internal static string typeEnum_configurationName_notifyBeforeExpiryNextRunDate {
            get {
                return ResourceManager.GetString("typeEnum.configurationName.notifyBeforeExpiryNextRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Days to Notify Before Expiry.
        /// </summary>
        internal static string typeEnum_configurationName_notifyDaysBeforeExpiry {
            get {
                return ResourceManager.GetString("typeEnum.configurationName.notifyDaysBeforeExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Days to Register By.
        /// </summary>
        internal static string typeEnum_configurationName_regFormalisationDaysDuration {
            get {
                return ResourceManager.GetString("typeEnum.configurationName.regFormalisationDaysDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admin Email.
        /// </summary>
        internal static string typeEnum_configurationName_systemAdminEmail {
            get {
                return ResourceManager.GetString("typeEnum.configurationName.systemAdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string typeEnum_contactRole_contact {
            get {
                return ResourceManager.GetString("typeEnum.contactRole.contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string typeEnum_creditusagemode_custom {
            get {
                return ResourceManager.GetString("typeEnum.creditusagemode.custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string typeEnum_creditusagemode_daily {
            get {
                return ResourceManager.GetString("typeEnum.creditusagemode.daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string typeEnum_creditusagemode_monthly {
            get {
                return ResourceManager.GetString("typeEnum.creditusagemode.monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string typeEnum_creditusagemode_weekly {
            get {
                return ResourceManager.GetString("typeEnum.creditusagemode.weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string typeEnum_creditusagemode_yearly {
            get {
                return ResourceManager.GetString("typeEnum.creditusagemode.yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string typeEnum_durationformat_day {
            get {
                return ResourceManager.GetString("typeEnum.durationformat.day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string typeEnum_durationformat_month {
            get {
                return ResourceManager.GetString("typeEnum.durationformat.month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string typeEnum_durationformat_year {
            get {
                return ResourceManager.GetString("typeEnum.durationformat.year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string typeEnum_emailConfigName_emailAddress {
            get {
                return ResourceManager.GetString("typeEnum.emailConfigName.emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SSL.
        /// </summary>
        internal static string typeEnum_emailConfigName_emailEnableSSL {
            get {
                return ResourceManager.GetString("typeEnum.emailConfigName.emailEnableSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string typeEnum_emailConfigName_emailHost {
            get {
                return ResourceManager.GetString("typeEnum.emailConfigName.emailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Name.
        /// </summary>
        internal static string typeEnum_emailConfigName_emailName {
            get {
                return ResourceManager.GetString("typeEnum.emailConfigName.emailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (Leave blank unless changes are intended).
        /// </summary>
        internal static string typeEnum_emailConfigName_emailPassword {
            get {
                return ResourceManager.GetString("typeEnum.emailConfigName.emailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string typeEnum_emailConfigName_emailPort {
            get {
                return ResourceManager.GetString("typeEnum.emailConfigName.emailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string typeEnum_gender_female {
            get {
                return ResourceManager.GetString("typeEnum.gender.female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string typeEnum_gender_male {
            get {
                return ResourceManager.GetString("typeEnum.gender.male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian Army Identity (BAT C. 10).
        /// </summary>
        internal static string typeEnum_idType_mys_armyID {
            get {
                return ResourceManager.GetString("typeEnum.idType.mys.armyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Malaysian Identity Card (MyKad).
        /// </summary>
        internal static string typeEnum_idType_mys_ic_new {
            get {
                return ResourceManager.GetString("typeEnum.idType.mys.ic.new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Malaysian Identity Card.
        /// </summary>
        internal static string typeEnum_idType_mys_ic_old {
            get {
                return ResourceManager.GetString("typeEnum.idType.mys.ic.old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian Birth Certificate (MyKid).
        /// </summary>
        internal static string typeEnum_idType_mys_mykid {
            get {
                return ResourceManager.GetString("typeEnum.idType.mys.mykid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian Police Identity.
        /// </summary>
        internal static string typeEnum_idType_mys_policeID {
            get {
                return ResourceManager.GetString("typeEnum.idType.mys.policeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian Permanent Resident (MyPR).
        /// </summary>
        internal static string typeEnum_idType_mys_pr {
            get {
                return ResourceManager.GetString("typeEnum.idType.mys.pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        internal static string typeEnum_idType_passport {
            get {
                return ResourceManager.GetString("typeEnum.idType.passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport (ICAO).
        /// </summary>
        internal static string typeEnum_idType_passport_icao {
            get {
                return ResourceManager.GetString("typeEnum.idType.passport.icao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorced.
        /// </summary>
        internal static string typeEnum_maritalStatus_divorced {
            get {
                return ResourceManager.GetString("typeEnum.maritalStatus.divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        internal static string typeEnum_maritalStatus_married {
            get {
                return ResourceManager.GetString("typeEnum.maritalStatus.married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string typeEnum_maritalStatus_single {
            get {
                return ResourceManager.GetString("typeEnum.maritalStatus.single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widowed.
        /// </summary>
        internal static string typeEnum_maritalStatus_widowed {
            get {
                return ResourceManager.GetString("typeEnum.maritalStatus.widowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string typeEnum_paymentinterval_monthly {
            get {
                return ResourceManager.GetString("typeEnum.paymentinterval.monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once.
        /// </summary>
        internal static string typeEnum_paymentinterval_once {
            get {
                return ResourceManager.GetString("typeEnum.paymentinterval.once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string typeEnum_paymentinterval_yearly {
            get {
                return ResourceManager.GetString("typeEnum.paymentinterval.yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Time.
        /// </summary>
        internal static string typeEnum_refferalCodeType_oneTime {
            get {
                return ResourceManager.GetString("typeEnum.refferalCodeType.oneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reusable.
        /// </summary>
        internal static string typeEnum_refferalCodeType_reusable {
            get {
                return ResourceManager.GetString("typeEnum.refferalCodeType.reusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string typeEnum_regStatus_expired {
            get {
                return ResourceManager.GetString("typeEnum.regStatus.expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string typeEnum_regStatus_pending {
            get {
                return ResourceManager.GetString("typeEnum.regStatus.pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        internal static string typeEnum_regStatus_registered {
            get {
                return ResourceManager.GetString("typeEnum.regStatus.registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string typeEnum_remindertype_after {
            get {
                return ResourceManager.GetString("typeEnum.remindertype.after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string typeEnum_remindertype_before {
            get {
                return ResourceManager.GetString("typeEnum.remindertype.before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string typeEnum_status_active {
            get {
                return ResourceManager.GetString("typeEnum.status.active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string typeEnum_status_deleted {
            get {
                return ResourceManager.GetString("typeEnum.status.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        internal static string typeEnum_status_suspended {
            get {
                return ResourceManager.GetString("typeEnum.status.suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Payment.
        /// </summary>
        internal static string typeEnum_transactiondescription_cashpayment {
            get {
                return ResourceManager.GetString("typeEnum.transactiondescription.cashpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire.
        /// </summary>
        internal static string typeEnum_transactiondescription_expire {
            get {
                return ResourceManager.GetString("typeEnum.transactiondescription.expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus+.
        /// </summary>
        internal static string typeEnum_transactiondescription_interest {
            get {
                return ResourceManager.GetString("typeEnum.transactiondescription.interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        internal static string typeEnum_transactiondescription_membership {
            get {
                return ResourceManager.GetString("typeEnum.transactiondescription.membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWallet Payment.
        /// </summary>
        internal static string typeEnum_transactiondescription_purchase {
            get {
                return ResourceManager.GetString("typeEnum.transactiondescription.purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWallet Topup.
        /// </summary>
        internal static string typeEnum_transactiondescription_topup {
            get {
                return ResourceManager.GetString("typeEnum.transactiondescription.topup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string typeEnum_unpaidaction_cancel {
            get {
                return ResourceManager.GetString("typeEnum.unpaidaction.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string typeEnum_unpaidaction_ignore {
            get {
                return ResourceManager.GetString("typeEnum.unpaidaction.ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn and Action.
        /// </summary>
        internal static string typeEnum_unpaidaction_warnandaction {
            get {
                return ResourceManager.GetString("typeEnum.unpaidaction.warnandaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string typeEnum_upgrademode_purchase {
            get {
                return ResourceManager.GetString("typeEnum.upgrademode.purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topup.
        /// </summary>
        internal static string typeEnum_upgrademode_topup {
            get {
                return ResourceManager.GetString("typeEnum.upgrademode.topup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Admin.
        /// </summary>
        internal static string typeEnum_userRole_branchAdmin {
            get {
                return ResourceManager.GetString("typeEnum.userRole.branchAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre Admin.
        /// </summary>
        internal static string typeEnum_userRole_centreAdmin {
            get {
                return ResourceManager.GetString("typeEnum.userRole.centreAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Admin.
        /// </summary>
        internal static string typeEnum_userRole_groupAdmin {
            get {
                return ResourceManager.GetString("typeEnum.userRole.groupAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Admin.
        /// </summary>
        internal static string typeEnum_userRole_userAdmin {
            get {
                return ResourceManager.GetString("typeEnum.userRole.userAdmin", resourceCulture);
            }
        }
    }
}
